### ISSUE TITLE
Symfony 1. Problem with sessions.

### ISSUE THREAD

**Issue by ruslan-polutsygan** [theodo/TheodoEvolutionLegacyWrapperBundle#17]
Hello,

Trying to use the bundle symfony 2.6, for migration project from symfony 1.4.
Look good. But session doesn't seem to working.

Is there any particular reason of regenerating session for each request -https://github.com/theodo/TheodoEvolutionLegacyWrapperBundle/blob/master/Kernel/Symfony14Kernel.php#L70

Thanks

**Comment by benja-M-1** [comment]
Hi @ruslan-polutsygan,

as far as I know, yes there a reason but I admit that I no longer remember why...

Do you think that it is the reason why your sessions doesn't work?
Did you tried the (TheodoEvolutionSessionBundle)[https://github.com/theodo/TheodoEvolutionSessionBundle]?

**Comment by ruslan-polutsygan** [comment]
Hi @benja-M-1 

Thanks for reply.

> I no longer remember why...

Happens :)
But if you remember why this is needed - I'll be happy to hear.

> Do you think that it is the reason why your sessions doesn't work?

Sorry for being confusing.. 
Sessions work I believe.
The problem is that symfony 1 uses session id for csrf tokens. And `$session->migrate()` eventually calls  
`session_regenerate_id` php function. Hence csrf token validation fails.
So, never mind - issue can be closed. I can cope with this on my own.

Thanks

**Comment by aar0nr** [comment]
I also don't understand why the session is being closed before dispatching to the legacy Symfony1.4 app. Shouldn't the legacy application reuse the existing session started from the Symfony2 app?

**Comment by benja-M-1** [comment]
Yes it should.

Did you try commenting that code? If it does would you mind send a PR and a way to reproduce the bug?

**Comment by aar0nr** [comment]
This is actually two problems...

The first part is a PHP7 only bug where session data is lost when a session is regenerated, but Symfony works around the bug by reloading the session data (https://git.io/voId4) after regeneration. I believe the problem is that without the ```TheodoEvolutionSessionBundle```, Symfony is not aware of the legacy session data and does not reload it back. If you install the session bundle, it seems to work.

The second part is that because the session id is being regenerated, I'm having the same problem as @ruslan-polutsygan where the legacy csrf does not work.

If you remove the ```$session->migrate()``` from https://git.io/voLk9, both problems go away.

PS. @ruslan-polutsygan can you share how you worked around the csrf problem?

**Comment by ruslan-polutsygan** [comment]
@aar0nr 

To be honest I can't remember what I did with it. It's been 1,5 years since then. And I don't work on the project any more.
Probably I used something else instead. Maybe I generated unique id myself.

**Comment by aar0nr** [comment]
@ruslan-polutsygan No problem. Thanks for responding. I ended up just extending the ```Symfony14Kernel``` to override the boot method. Not ideal, but works for now.
